language: cpp
sudo: required
dist: trusty

env:
    - IMAGE=debian_9 PROFILE_RELEASE=deb9_gcc_release PROFILE_DEBUG=deb9_gcc_debug
    - IMAGE=docker-debian-8 PROFILE_RELEASE=deb8_gcc_release PROFILE_DEBUG=deb8_gcc_debug


services:
    - docker
    
    
before_install:
    #
    # before we can do anything else we have to start the docker container
    #
    - docker run --name build -i -d -v"$PWD:/src" eugenwintersberger/$IMAGE:latest
    
install:
    #
    # install the requested packages for Debug and Release builds
    #
    
    - docker exec -e PROFILE_RELEASE -it build bash -c "conan install -b missing --profile ./profiles/$PROFILE_RELEASE conanfile_devel.txt"
    - docker exec -e PROFILE_DEBUG -it build bash -c "conan install -b missing --profile ./profiles/$PROFILE_DEBUG conanfile_devel.txt"
    
script:
    #
    # upload the packages to my bintray repository for DESY packages
    #
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages Boost/1.62.0@lasote/stable"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages hdf5/1.10.1@eugenwintersberger/testing"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages gtest/1.8.0@conan/stable"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages zlib/1.2.8@conan/stable"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages bzip2/1.0.6@conan/stable"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages h5cpp/master@eugenwintersberger/devel"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages pnicore/master@eugenwintersberger/devel"
    #- docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --force --all -r desypackages pniio/master@eugenwintersberger/devel"
    
after_script:
    - docker container stop build
    
